version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:10.13
    working_directory: /repo

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules
  build:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
        at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - package
  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn lint && yarn test
  release:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: yarn release

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          filters:
            branches:
              only:
                - master
                - continuous-deployment # TODO: remove
          requires:
            - test
            - build
